#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.socat
	set firewall.socat=include
	set firewall.socat.type=nftables
	set firewall.socat.path=/var/etc/socat.nft
	set firewall.socat.position=table-pre
EOF

rm -rf /tmp/luci-*cache
exit 0
